 version: "3"
 services:
  backend:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - 5000:5000
    env_file: ./.env
    volumes:
      - ./:/usr/src/app:ro
      - /usr/src/app/node_modules
      - /usr/src/app/frontend
    depends_on: 
      - mongodb
    environment:
      # https://github.com/privatenumber/tsx/issues/266#issuecomment-2074009982
      - CHOKIDAR_USEPOLLING=true 
    command: npm run dev
  mongodb:
    image: "mongo:latest"
    env_file:
      - ./.env
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db
      - mongo-config:/data/configdb
 
 volumes:
  mongo-db:
  mongo-config: